#!/bin/sh
printf "remounting\n"
mount -o rw,remount /

rm /userdata/YouDaoManager

rm /etc/init.d/S75YouDaoMgr


wget -O /userdata/YouDaoManager https://ghproxy.com/https://github.com/ljlVink/YouDaoDict_go/releases/latest/download/YouDaoManager 
chmod 777 /userdata/YouDaoManager
wget  -O /etc/init.d/S75YouDaoMgr https://ghproxy.com/https://raw.githubusercontent.com/ljlVink/YouDaoDict_go/main/S75YouDaoMgr
chmod 777 /etc/init.d/S75YouDaoMgr
reboot