#!/bin/sh
wget https://ghproxy.com/https://github.com/ljlVink/YouDaoDict_go/releases/latest/download/YouDaoManager -O /userdata
chmod 777 /userdata/YouDaoManager
mount -o remount -rw /
wget https://ghproxy.com/https://raw.githubusercontent.com/ljlVink/YouDaoDict_go/main/S75YouDaoMgr -O /etc/init.d
chmod 777 /etc/init.d/S75YouDaoMgr