# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Set env vars
      run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "GOOS=linux" >> $GITHUB_ENV
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "GOARM=7" >> $GITHUB_ENV


    - name: Build
      run: go build -o YouDaoManager

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: YouDaoManager
        path: YouDaoManager
